package registry

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"sort"
	"strings"
	"time"
)

// Candidates is the human-maintained input to Refresh.
type Candidates struct {
	Runtime struct {
		Repo             string            `json:"repo"`
		License          string            `json:"license"`
		RefreshAfterDays int               `json:"refresh_after_days"`
		Assets           map[string]string `json:"assets"` // "os/arch" -> name pattern with {tag}
	} `json:"runtime"`
	Discover struct {
		MaxParamsB float64  `json:"max_params_b"`
		GGUFOrgs   []string `json:"gguf_orgs"`
	} `json:"discover"`
	Candidates []Candidate `json:"candidates"`
}

type Candidate struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Upstream    string            `json:"upstream"`
	Repo        string            `json:"repo"`
	Quant       string            `json:"quant"`
	Files       map[string]string `json:"files"`
	Caps        []string          `json:"caps"`
	Context     int               `json:"context"`
	Args        []string          `json:"args,omitempty"`
	OutputAfter string            `json:"output_after,omitempty"`
	Notes       string            `json:"notes,omitempty"`
	// RAMOverheadMB overrides the policy's estimate overhead for runtimes
	// whose memory use is not dominated by the weights.
	RAMOverheadMB int `json:"ram_overhead_mb,omitempty"`
}

// Source provides upstream facts. HF implements it over HTTPS; tests use a
// fixture server.
type Source interface {
	RepoFiles(ctx context.Context, repo string) (revision string, files map[string]RemoteFile, err error)
	Upstream(ctx context.Context, id string) (UpstreamInfo, error)
	LatestRelease(ctx context.Context, repo string) (Release, error)
	Leaderboard(ctx context.Context, dataset string) ([]LeaderboardEntry, error)
	Exists(ctx context.Context, repo string) bool
}

type RemoteFile struct {
	SHA256 string
	Size   int64
}

type UpstreamInfo struct {
	License string
	ParamsB float64
	Evals   []Eval
}

// Eval is one entry of a Hugging Face model's evalResults.
type Eval struct {
	Dataset  string
	Task     string
	Value    float64
	Verified bool
	Source   string
	URL      string
	Date     string
}

type Release struct {
	Tag       string
	Published time.Time
	Assets    map[string]RemoteAsset
}

type RemoteAsset struct {
	URL    string
	SHA256 string
	Size   int64
}

type LeaderboardEntry struct {
	ModelID string  `json:"modelId"`
	Value   float64 `json:"value"`
	Params  int64   `json:"num_parameters"`
}

// RefreshOptions controls a refresh run.
type RefreshOptions struct {
	Now     time.Time
	Runtime bool // allow bumping the runtime pin
}

// Refresh rebuilds the registry from candidates and policy using upstream
// data. A candidate whose upstream data cannot be fetched keeps its previous
// entry unchanged. The version only changes when content changes, so a
// no-op refresh yields a byte-identical file.
func Refresh(ctx context.Context, prev *Registry, pol Policy, cands Candidates, src Source, opt RefreshOptions) (*Registry, []string, error) {
	var warn []string
	next := &Registry{
		Schema:  Schema,
		Version: prev.Version,
		Note:    "Generated by cmd/mote-refresh from registry/candidates.json and registry/policy.json. Benchmarks are upstream measurements (Hugging Face evalResults) unless kind says otherwise; ram_mb_estimate is an estimate (file size + policy overhead).",
		Runtime: prev.Runtime,
		Policy:  pol,
	}

	if opt.Runtime {
		rt, w, err := refreshRuntime(ctx, prev.Runtime, cands, src, opt.Now)
		if err != nil {
			warn = append(warn, "runtime: "+err.Error()+"; keeping "+prev.Runtime.Version)
		} else {
			next.Runtime = rt
			warn = append(warn, w...)
		}
	}

	ok := 0
	for _, c := range cands.Candidates {
		m, err := buildModel(ctx, c, pol, src)
		if err != nil {
			if old, found := prev.Model(c.ID); found {
				warn = append(warn, fmt.Sprintf("%s: %v; keeping previous entry", c.ID, err))
				next.Models = append(next.Models, *old)
			} else {
				warn = append(warn, fmt.Sprintf("%s: %v; skipped", c.ID, err))
			}
			continue
		}
		ok++
		next.Models = append(next.Models, m)
	}
	if ok == 0 && len(cands.Candidates) > 0 {
		return nil, warn, fmt.Errorf("no candidate could be refreshed; upstream unavailable")
	}
	next.Defaults = next.ComputeDefaults()

	if sameContent(prev, next) {
		next.Version, next.Generated = prev.Version, prev.Generated
	} else {
		next.Version = nextVersion(prev.Version, opt.Now)
		next.Generated = opt.Now.UTC().Format(time.RFC3339)
	}
	if err := next.Validate(); err != nil {
		return nil, warn, err
	}
	return next, warn, nil
}

func buildModel(ctx context.Context, c Candidate, pol Policy, src Source) (Model, error) {
	rev, remote, err := src.RepoFiles(ctx, c.Repo)
	if err != nil {
		return Model{}, err
	}
	up, err := src.Upstream(ctx, c.Upstream)
	if err != nil {
		return Model{}, err
	}
	m := Model{
		ID: c.ID, Name: c.Name, Backend: "llama.cpp", Upstream: c.Upstream,
		Repo: c.Repo, Revision: rev, License: up.License, Quant: c.Quant,
		ParamsB: math.Round(up.ParamsB*100) / 100, Caps: c.Caps, Context: c.Context,
		Args: c.Args, OutputAfter: c.OutputAfter, Notes: c.Notes, Benchmarks: []Benchmark{},
	}
	for _, role := range []string{"model", "mmproj"} {
		name, ok := c.Files[role]
		if !ok {
			continue
		}
		rf, ok := remote[name]
		if !ok || rf.SHA256 == "" {
			return Model{}, fmt.Errorf("%s: file %s not found upstream", c.Repo, name)
		}
		m.Files = append(m.Files, File{
			Role: role, Name: name, SHA256: rf.SHA256, Size: rf.Size,
			URL: fmt.Sprintf("https://huggingface.co/%s/resolve/%s/%s", c.Repo, rev, name),
		})
	}
	mib := int((m.Bytes() + (1<<20 - 1)) >> 20)
	overhead := pol.RAMOverheadMB
	if c.RAMOverheadMB > 0 {
		overhead = c.RAMOverheadMB
	}
	m.RAMEstimate = mib + overhead
	m.MinRAMMB = int(math.Ceil(float64(m.RAMEstimate)/pol.UsableRAMFraction/512)) * 512

	// Record only the metrics the policy gates on, one entry per metric.
	need := map[[2]string]bool{}
	for _, g := range pol.Gates {
		need[[2]string{g.Dataset, g.Task}] = true
	}
	best := map[[2]string]Eval{}
	for _, e := range up.Evals {
		k := [2]string{e.Dataset, e.Task}
		if !need[k] {
			continue
		}
		if cur, ok := best[k]; !ok || preferEval(e, cur) {
			best[k] = e
		}
	}
	for _, e := range best {
		m.Benchmarks = append(m.Benchmarks, Benchmark{
			Kind: KindUpstream, Dataset: e.Dataset, Task: e.Task, Value: e.Value,
			Verified: e.Verified, Source: e.Source, URL: e.URL, Date: e.Date,
		})
	}
	sort.Slice(m.Benchmarks, func(i, j int) bool {
		a, b := m.Benchmarks[i], m.Benchmarks[j]
		return a.Dataset+"/"+a.Task < b.Dataset+"/"+b.Task
	})
	return m, nil
}

// preferEval orders duplicate upstream results deterministically: verified
// first, then most recent, then source name.
func preferEval(a, b Eval) bool {
	if a.Verified != b.Verified {
		return a.Verified
	}
	if a.Date != b.Date {
		return a.Date > b.Date
	}
	return a.Source < b.Source
}

func refreshRuntime(ctx context.Context, prev Runtime, cands Candidates, src Source, now time.Time) (Runtime, []string, error) {
	rel, err := src.LatestRelease(ctx, cands.Runtime.Repo)
	if err != nil {
		return prev, nil, err
	}
	if rel.Tag == prev.Version {
		return prev, nil, nil
	}
	if prev.Version != "" && cands.Runtime.RefreshAfterDays > 0 {
		if pub, err := time.Parse("2006-01-02", prev.Published); err == nil &&
			now.Sub(pub) < time.Duration(cands.Runtime.RefreshAfterDays)*24*time.Hour {
			return prev, nil, nil
		}
	}
	rt := Runtime{
		Name: "llama.cpp", Version: rel.Tag, License: cands.Runtime.License,
		Published: rel.Published.UTC().Format("2006-01-02"),
		Source:    "https://github.com/" + cands.Runtime.Repo + "/releases/tag/" + rel.Tag,
	}
	keys := make([]string, 0, len(cands.Runtime.Assets))
	for k := range cands.Runtime.Assets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		name := strings.ReplaceAll(cands.Runtime.Assets[k], "{tag}", rel.Tag)
		a, ok := rel.Assets[name]
		if !ok || a.SHA256 == "" {
			return prev, nil, fmt.Errorf("release %s lacks %s or its digest", rel.Tag, name)
		}
		goos, arch, _ := strings.Cut(k, "/")
		rt.Assets = append(rt.Assets, Asset{OS: goos, Arch: arch, URL: a.URL, SHA256: a.SHA256, Size: a.Size})
	}
	return rt, []string{fmt.Sprintf("runtime: %s -> %s", prev.Version, rel.Tag)}, nil
}

func sameContent(a, b *Registry) bool {
	strip := func(r *Registry) []byte {
		c := *r
		c.Version, c.Generated = "", ""
		out, _ := json.Marshal(c)
		return out
	}
	return bytes.Equal(strip(a), strip(b))
}

func nextVersion(prev string, now time.Time) string {
	day := now.UTC().Format("2006.01.02")
	if !strings.HasPrefix(prev, day) {
		return day
	}
	n := 1
	if _, suf, ok := strings.Cut(strings.TrimPrefix(prev, day), "."); ok {
		fmt.Sscanf(suf, "%d", &n)
		n++
	}
	return fmt.Sprintf("%s.%d", day, n)
}

// Encode renders a registry the way it is stored in the repository.
func Encode(r *Registry) []byte {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	_ = enc.Encode(r)
	return buf.Bytes()
}

// Discovered is a model found on a gate leaderboard that is not yet a
// candidate. It is a report for maintainers, never used for selection.
type Discovered struct {
	Upstream string  `json:"upstream"`
	ParamsB  float64 `json:"params_b"`
	Dataset  string  `json:"dataset"`
	Task     string  `json:"task"`
	Value    float64 `json:"value"`
	GGUF     string  `json:"gguf_repo,omitempty"`
}

// Discover lists small models with upstream results on the policy's gate
// benchmarks that are not candidates yet.
func Discover(ctx context.Context, pol Policy, cands Candidates, src Source) ([]Discovered, error) {
	known := map[string]bool{}
	for _, c := range cands.Candidates {
		known[c.Upstream] = true
	}
	datasets := map[string]Gate{}
	for _, g := range pol.Gates {
		datasets[g.Dataset] = g
	}
	var names []string
	for d := range datasets {
		names = append(names, d)
	}
	sort.Strings(names)
	limit := int64(cands.Discover.MaxParamsB * 1e9)
	var out []Discovered
	for _, d := range names {
		rows, err := src.Leaderboard(ctx, d)
		if err != nil {
			return nil, fmt.Errorf("leaderboard %s: %w", d, err)
		}
		for _, r := range rows {
			if r.Params <= 0 || r.Params > limit || known[r.ModelID] {
				continue
			}
			known[r.ModelID] = true
			item := Discovered{Upstream: r.ModelID, ParamsB: math.Round(float64(r.Params)/1e7) / 100,
				Dataset: d, Task: datasets[d].Task, Value: r.Value}
			base := r.ModelID[strings.LastIndex(r.ModelID, "/")+1:]
			for _, org := range cands.Discover.GGUFOrgs {
				if repo := org + "/" + base + "-GGUF"; src.Exists(ctx, repo) {
					item.GGUF = repo
					break
				}
			}
			out = append(out, item)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Dataset != out[j].Dataset {
			return out[i].Dataset < out[j].Dataset
		}
		return out[i].Upstream < out[j].Upstream
	})
	return out, nil
}

// HF is a Source backed by the public Hugging Face and GitHub HTTP APIs. No
// credentials are needed; GitHubToken only raises rate limits.
type HF struct {
	Client      *http.Client
	HFBase      string // default https://huggingface.co
	GitHubBase  string // default https://api.github.com
	GitHubToken string
}

func (h *HF) hf() string {
	if h.HFBase != "" {
		return h.HFBase
	}
	return "https://huggingface.co"
}

func (h *HF) gh() string {
	if h.GitHubBase != "" {
		return h.GitHubBase
	}
	return "https://api.github.com"
}

func (h *HF) get(ctx context.Context, u string, v any, auth string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return err
	}
	req.Header.Set("User-Agent", "mote-refresh")
	if auth != "" {
		req.Header.Set("Authorization", "Bearer "+auth)
	}
	c := h.Client
	if c == nil {
		c = &http.Client{Timeout: 60 * time.Second}
	}
	resp, err := c.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		io.Copy(io.Discard, resp.Body)
		return fmt.Errorf("GET %s: %s", u, resp.Status)
	}
	return json.NewDecoder(io.LimitReader(resp.Body, 64<<20)).Decode(v)
}

func (h *HF) RepoFiles(ctx context.Context, repo string) (string, map[string]RemoteFile, error) {
	var info struct {
		SHA string `json:"sha"`
	}
	if err := h.get(ctx, h.hf()+"/api/models/"+repo+"?expand[]=sha", &info, ""); err != nil {
		return "", nil, err
	}
	if len(info.SHA) != 40 {
		return "", nil, fmt.Errorf("%s: no revision", repo)
	}
	var tree []struct {
		Path string `json:"path"`
		Size int64  `json:"size"`
		LFS  *struct {
			OID string `json:"oid"`
		} `json:"lfs"`
	}
	if err := h.get(ctx, h.hf()+"/api/models/"+repo+"/tree/"+info.SHA, &tree, ""); err != nil {
		return "", nil, err
	}
	files := map[string]RemoteFile{}
	for _, f := range tree {
		if f.LFS != nil {
			files[f.Path] = RemoteFile{SHA256: f.LFS.OID, Size: f.Size}
		}
	}
	return info.SHA, files, nil
}

func (h *HF) Upstream(ctx context.Context, id string) (UpstreamInfo, error) {
	var d struct {
		CardData struct {
			License string `json:"license"`
		} `json:"cardData"`
		Safetensors struct {
			Total int64 `json:"total"`
		} `json:"safetensors"`
		EvalResults []struct {
			Filename string `json:"filename"`
			Verified bool   `json:"verified"`
			Data     struct {
				Dataset struct {
					ID     string `json:"id"`
					TaskID string `json:"task_id"`
				} `json:"dataset"`
				Value  *float64 `json:"value"`
				Date   string   `json:"date"`
				Source struct {
					URL  string `json:"url"`
					Name string `json:"name"`
					User string `json:"user"`
				} `json:"source"`
			} `json:"data"`
		} `json:"evalResults"`
	}
	q := "?expand[]=cardData&expand[]=safetensors&expand[]=evalResults"
	if err := h.get(ctx, h.hf()+"/api/models/"+id+q, &d, ""); err != nil {
		return UpstreamInfo{}, err
	}
	if d.CardData.License == "" {
		return UpstreamInfo{}, fmt.Errorf("%s: license not declared upstream", id)
	}
	info := UpstreamInfo{License: d.CardData.License, ParamsB: float64(d.Safetensors.Total) / 1e9}
	for _, e := range d.EvalResults {
		x := e.Data
		if x.Value == nil || x.Dataset.ID == "" || x.Date == "" {
			continue
		}
		src := x.Source.Name
		if src == "" {
			src = x.Source.User
		}
		u := x.Source.URL
		if !strings.HasPrefix(u, "https://") {
			u = "https://huggingface.co/" + id + "/blob/main/" + url.PathEscape(e.Filename)
		}
		date := x.Date
		if len(date) > 10 {
			date = date[:10]
		}
		info.Evals = append(info.Evals, Eval{Dataset: x.Dataset.ID, Task: x.Dataset.TaskID, Value: *x.Value,
			Verified: e.Verified, Source: src, URL: u, Date: date})
	}
	return info, nil
}

func (h *HF) LatestRelease(ctx context.Context, repo string) (Release, error) {
	var d struct {
		Tag       string    `json:"tag_name"`
		Published time.Time `json:"published_at"`
		Assets    []struct {
			Name   string `json:"name"`
			URL    string `json:"browser_download_url"`
			Size   int64  `json:"size"`
			Digest string `json:"digest"`
		} `json:"assets"`
	}
	if err := h.get(ctx, h.gh()+"/repos/"+repo+"/releases/latest", &d, h.GitHubToken); err != nil {
		return Release{}, err
	}
	rel := Release{Tag: d.Tag, Published: d.Published, Assets: map[string]RemoteAsset{}}
	for _, a := range d.Assets {
		rel.Assets[a.Name] = RemoteAsset{URL: a.URL, Size: a.Size, SHA256: strings.TrimPrefix(a.Digest, "sha256:")}
	}
	return rel, nil
}

func (h *HF) Leaderboard(ctx context.Context, dataset string) ([]LeaderboardEntry, error) {
	var rows []LeaderboardEntry
	err := h.get(ctx, h.hf()+"/api/datasets/"+dataset+"/leaderboard", &rows, "")
	return rows, err
}

func (h *HF) Exists(ctx context.Context, repo string) bool {
	var v map[string]any
	return h.get(ctx, h.hf()+"/api/models/"+repo, &v, "") == nil
}
