package registry

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"path"
	"sort"
	"strings"
	"time"
)

// RuntimeSource says where a runtime's releases come from.
type RuntimeSource struct {
	Repo             string `json:"repo"`
	License          string `json:"license"`
	RefreshAfterDays int    `json:"refresh_after_days"`
	// Assets maps "os/arch" to the asset's name: {tag} stands for the
	// release tag, and * for any text (sd.cpp names its macOS build after
	// the macOS version it was built on). Exactly one asset must match.
	Assets map[string]string `json:"assets"`
}

// Candidates is the human-maintained input to Refresh.
type Candidates struct {
	Runtime RuntimeSource `json:"runtime"`
	// Runtimes are the other backends' runtimes, by backend name.
	Runtimes map[string]RuntimeSource `json:"runtimes,omitempty"`
	Discover struct {
		MaxParamsB float64  `json:"max_params_b"`
		GGUFOrgs   []string `json:"gguf_orgs"`
	} `json:"discover"`
	Candidates []Candidate `json:"candidates"`
}

type Candidate struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Backend  string `json:"backend,omitempty"` // llama.cpp when empty
	Upstream string `json:"upstream"`
	Repo     string `json:"repo"`
	Quant    string `json:"quant"`
	// Files maps a role to a file in Repo, or to {"repo", "file"} for one
	// kept elsewhere: an image model's text encoder and VAE usually are.
	Files       map[string]FileSpec `json:"files"`
	Caps        []string            `json:"caps"`
	Context     int                 `json:"context"`
	Args        []string            `json:"args,omitempty"`
	OutputAfter string              `json:"output_after,omitempty"`
	QueryPrefix string              `json:"query_prefix,omitempty"`
	Notes       string              `json:"notes,omitempty"`
	// RAMOverheadMB overrides the policy's estimate overhead for runtimes
	// whose memory use is not dominated by the weights.
	RAMOverheadMB int `json:"ram_overhead_mb,omitempty"`
}

// FileSpec is a file of a candidate, in its own repo or another.
type FileSpec struct {
	Repo string `json:"repo,omitempty"`
	File string `json:"file"`
}

// UnmarshalJSON accepts a bare file name as well as the object form.
func (f *FileSpec) UnmarshalJSON(b []byte) error {
	var name string
	if json.Unmarshal(b, &name) == nil {
		*f = FileSpec{File: name}
		return nil
	}
	type plain FileSpec
	var p plain
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&p); err != nil {
		return err
	}
	if p.File == "" {
		return fmt.Errorf("file spec %s has no file", b)
	}
	*f = FileSpec(p)
	return nil
}

// Source provides upstream facts. HF implements it over HTTPS; tests use a
// fixture server.
type Source interface {
	RepoFiles(ctx context.Context, repo string) (revision string, files map[string]RemoteFile, err error)
	Upstream(ctx context.Context, id string) (UpstreamInfo, error)
	LatestRelease(ctx context.Context, repo string) (Release, error)
	Leaderboard(ctx context.Context, dataset string) ([]LeaderboardEntry, error)
	Exists(ctx context.Context, repo string) bool
}

type RemoteFile struct {
	SHA256 string
	Size   int64
}

type UpstreamInfo struct {
	License string
	ParamsB float64
	Evals   []Eval
}

// Eval is one entry of a Hugging Face model's evalResults.
type Eval struct {
	Dataset  string
	Task     string
	Value    float64
	Verified bool
	Source   string
	URL      string
	Date     string
}

type Release struct {
	Tag       string
	Published time.Time
	Assets    map[string]RemoteAsset
}

type RemoteAsset struct {
	URL    string
	SHA256 string
	Size   int64
}

type LeaderboardEntry struct {
	ModelID string  `json:"modelId"`
	Value   float64 `json:"value"`
	Params  int64   `json:"num_parameters"`
}

// RefreshOptions controls a refresh run.
type RefreshOptions struct {
	Now     time.Time
	Runtime bool // allow bumping the runtime pin
}

// Refresh rebuilds the registry from candidates and policy using upstream
// data. A candidate whose upstream data cannot be fetched keeps its previous
// entry unchanged. The version only changes when content changes, so a
// no-op refresh yields a byte-identical file.
func Refresh(ctx context.Context, prev *Registry, pol Policy, cands Candidates, src Source, opt RefreshOptions) (*Registry, []string, error) {
	var warn []string
	next := &Registry{
		Schema:  Schema,
		Version: prev.Version,
		Note:    "Generated by cmd/mote-refresh from registry/candidates.json and registry/policy.json. Benchmarks are upstream measurements (Hugging Face evalResults) unless kind says otherwise; ram_mb_estimate is an estimate (file size + policy overhead).",
		Runtime: prev.Runtime,
		Policy:  pol,
	}

	if opt.Runtime {
		rt, w, err := refreshRuntime(ctx, "llama.cpp", prev.Runtime, cands.Runtime, src, opt.Now)
		if err != nil {
			warn = append(warn, "runtime: "+err.Error()+"; keeping "+prev.Runtime.Version)
		} else {
			next.Runtime = rt
			warn = append(warn, w...)
		}
	}
	// Other runtimes follow the same rule, and one that is new is pinned
	// whether or not bumps were asked for: a model cannot run without it.
	names := make([]string, 0, len(cands.Runtimes))
	for n := range cands.Runtimes {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		old, had := prev.RuntimeFor(name)
		if had && !opt.Runtime {
			next.Runtimes = append(next.Runtimes, old)
			continue
		}
		rt, w, err := refreshRuntime(ctx, name, old, cands.Runtimes[name], src, opt.Now)
		switch {
		case err != nil && had:
			warn = append(warn, name+": "+err.Error()+"; keeping "+old.Version)
			next.Runtimes = append(next.Runtimes, old)
		case err != nil:
			warn = append(warn, name+": "+err.Error()+"; its models cannot be offered")
		default:
			next.Runtimes = append(next.Runtimes, rt)
			warn = append(warn, w...)
		}
	}

	ok := 0
	for _, c := range cands.Candidates {
		if c.Backend != "" && c.Backend != "llama.cpp" {
			if _, ok := next.RuntimeFor(c.Backend); !ok {
				warn = append(warn, fmt.Sprintf("%s: no %s runtime is pinned; skipped", c.ID, c.Backend))
				continue
			}
		}
		m, err := buildModel(ctx, c, pol, src)
		if err != nil {
			if old, found := prev.Model(c.ID); found {
				warn = append(warn, fmt.Sprintf("%s: %v; keeping previous entry", c.ID, err))
				next.Models = append(next.Models, *old)
			} else {
				warn = append(warn, fmt.Sprintf("%s: %v; skipped", c.ID, err))
			}
			continue
		}
		ok++
		next.Models = append(next.Models, m)
	}
	if ok == 0 && len(cands.Candidates) > 0 {
		return nil, warn, fmt.Errorf("no candidate could be refreshed; upstream unavailable")
	}
	next.Defaults = next.ComputeDefaults()

	if sameContent(prev, next) {
		next.Version, next.Generated = prev.Version, prev.Generated
	} else {
		next.Version = nextVersion(prev.Version, opt.Now)
		next.Generated = opt.Now.UTC().Format(time.RFC3339)
	}
	if err := next.Validate(); err != nil {
		return nil, warn, err
	}
	return next, warn, nil
}

func buildModel(ctx context.Context, c Candidate, pol Policy, src Source) (Model, error) {
	rev, remote, err := src.RepoFiles(ctx, c.Repo)
	if err != nil {
		return Model{}, err
	}
	up, err := src.Upstream(ctx, c.Upstream)
	if err != nil {
		return Model{}, err
	}
	backend := c.Backend
	if backend == "" {
		backend = "llama.cpp"
	}
	m := Model{
		ID: c.ID, Name: c.Name, Backend: backend, Upstream: c.Upstream,
		Repo: c.Repo, Revision: rev, License: up.License, Quant: c.Quant,
		ParamsB: math.Round(up.ParamsB*100) / 100, Caps: c.Caps, Context: c.Context,
		Args: c.Args, OutputAfter: c.OutputAfter, QueryPrefix: c.QueryPrefix, Notes: c.Notes, Benchmarks: []Benchmark{},
	}
	// Each other repo is pinned to its own current revision, like the
	// candidate's.
	type pinned struct {
		rev   string
		files map[string]RemoteFile
	}
	repos := map[string]pinned{c.Repo: {rev, remote}}
	for _, role := range []string{"model", "mmproj", "vae", "llm"} {
		spec, ok := c.Files[role]
		if !ok {
			continue
		}
		repo := spec.Repo
		if repo == "" {
			repo = c.Repo
		}
		p, ok := repos[repo]
		if !ok {
			r, files, err := src.RepoFiles(ctx, repo)
			if err != nil {
				return Model{}, err
			}
			p = pinned{r, files}
			repos[repo] = p
		}
		rf, ok := p.files[spec.File]
		if !ok || rf.SHA256 == "" {
			return Model{}, fmt.Errorf("%s: file %s not found upstream", repo, spec.File)
		}
		// Stored under its base name: the VAE of a diffusers repo lives
		// in a vae/ folder, which the local layout does not need.
		m.Files = append(m.Files, File{
			Role: role, Name: path.Base(spec.File), SHA256: rf.SHA256, Size: rf.Size,
			URL: fmt.Sprintf("https://huggingface.co/%s/resolve/%s/%s", repo, p.rev, spec.File),
		})
	}
	mib := int((m.Bytes() + (1<<20 - 1)) >> 20)
	overhead := pol.RAMOverheadMB
	if c.RAMOverheadMB > 0 {
		overhead = c.RAMOverheadMB
	}
	m.RAMEstimate = mib + overhead
	m.MinRAMMB = int(math.Ceil(float64(m.RAMEstimate)/pol.UsableRAMFraction/512)) * 512

	// Record only the metrics the policy gates on, one entry per metric.
	need := map[[2]string]bool{}
	for _, g := range pol.Gates {
		need[[2]string{g.Dataset, g.Task}] = true
	}
	best := map[[2]string]Eval{}
	for _, e := range up.Evals {
		k := [2]string{e.Dataset, e.Task}
		if !need[k] {
			continue
		}
		if cur, ok := best[k]; !ok || preferEval(e, cur) {
			best[k] = e
		}
	}
	for _, e := range best {
		m.Benchmarks = append(m.Benchmarks, Benchmark{
			Kind: KindUpstream, Dataset: e.Dataset, Task: e.Task, Value: e.Value,
			Verified: e.Verified, Source: e.Source, URL: e.URL, Date: e.Date,
		})
	}
	sort.Slice(m.Benchmarks, func(i, j int) bool {
		a, b := m.Benchmarks[i], m.Benchmarks[j]
		return a.Dataset+"/"+a.Task < b.Dataset+"/"+b.Task
	})
	return m, nil
}

// preferEval orders duplicate upstream results deterministically: verified
// first, then most recent, then source name.
func preferEval(a, b Eval) bool {
	if a.Verified != b.Verified {
		return a.Verified
	}
	if a.Date != b.Date {
		return a.Date > b.Date
	}
	return a.Source < b.Source
}

func refreshRuntime(ctx context.Context, name string, prev Runtime, spec RuntimeSource, src Source, now time.Time) (Runtime, []string, error) {
	rel, err := src.LatestRelease(ctx, spec.Repo)
	if err != nil {
		return prev, nil, err
	}
	if rel.Tag == prev.Version {
		return prev, nil, nil
	}
	if prev.Version != "" && spec.RefreshAfterDays > 0 {
		if pub, err := time.Parse("2006-01-02", prev.Published); err == nil &&
			now.Sub(pub) < time.Duration(spec.RefreshAfterDays)*24*time.Hour {
			return prev, nil, nil
		}
	}
	rt := Runtime{
		Name: name, Version: rel.Tag, License: spec.License,
		Published: rel.Published.UTC().Format("2006-01-02"),
		Source:    "https://github.com/" + spec.Repo + "/releases/tag/" + rel.Tag,
	}
	keys := make([]string, 0, len(spec.Assets))
	for k := range spec.Assets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		a, err := matchAsset(rel, strings.ReplaceAll(spec.Assets[k], "{tag}", rel.Tag))
		if err != nil {
			return prev, nil, err
		}
		goos, arch, _ := strings.Cut(k, "/")
		rt.Assets = append(rt.Assets, Asset{OS: goos, Arch: arch, URL: a.URL, SHA256: a.SHA256, Size: a.Size})
	}
	was := prev.Version
	if was == "" {
		was = "none"
	}
	return rt, []string{fmt.Sprintf("%s: %s -> %s", name, was, rel.Tag)}, nil
}

// matchAsset finds the one asset of a release whose name matches pattern,
// in which * stands for any text.
func matchAsset(rel Release, pattern string) (RemoteAsset, error) {
	var found []string
	for n := range rel.Assets {
		if ok, _ := path.Match(pattern, n); ok {
			found = append(found, n)
		}
	}
	switch len(found) {
	case 0:
		return RemoteAsset{}, fmt.Errorf("release %s has no asset matching %s", rel.Tag, pattern)
	case 1:
	default:
		sort.Strings(found)
		return RemoteAsset{}, fmt.Errorf("release %s has several assets matching %s: %s", rel.Tag, pattern, strings.Join(found, ", "))
	}
	a := rel.Assets[found[0]]
	if a.SHA256 == "" {
		return RemoteAsset{}, fmt.Errorf("release %s lacks a digest for %s", rel.Tag, found[0])
	}
	return a, nil
}

func sameContent(a, b *Registry) bool {
	strip := func(r *Registry) []byte {
		c := *r
		c.Version, c.Generated = "", ""
		out, _ := json.Marshal(c)
		return out
	}
	return bytes.Equal(strip(a), strip(b))
}

func nextVersion(prev string, now time.Time) string {
	day := now.UTC().Format("2006.01.02")
	if !strings.HasPrefix(prev, day) {
		return day
	}
	n := 1
	if _, suf, ok := strings.Cut(strings.TrimPrefix(prev, day), "."); ok {
		fmt.Sscanf(suf, "%d", &n)
		n++
	}
	return fmt.Sprintf("%s.%d", day, n)
}

// Encode renders a registry the way it is stored in the repository.
func Encode(r *Registry) []byte {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	_ = enc.Encode(r)
	return buf.Bytes()
}

// Discovered is a model found on a gate leaderboard that is not yet a
// candidate. It is a report for maintainers, never used for selection.
type Discovered struct {
	Upstream string  `json:"upstream"`
	ParamsB  float64 `json:"params_b"`
	Dataset  string  `json:"dataset"`
	Task     string  `json:"task"`
	Value    float64 `json:"value"`
	GGUF     string  `json:"gguf_repo,omitempty"`
}

// Discover lists small models with upstream results on the policy's gate
// benchmarks that are not candidates yet.
func Discover(ctx context.Context, pol Policy, cands Candidates, src Source) ([]Discovered, error) {
	known := map[string]bool{}
	for _, c := range cands.Candidates {
		known[c.Upstream] = true
	}
	datasets := map[string]Gate{}
	for _, g := range pol.Gates {
		datasets[g.Dataset] = g
	}
	var names []string
	for d := range datasets {
		names = append(names, d)
	}
	sort.Strings(names)
	limit := int64(cands.Discover.MaxParamsB * 1e9)
	var out []Discovered
	for _, d := range names {
		rows, err := src.Leaderboard(ctx, d)
		if err != nil {
			return nil, fmt.Errorf("leaderboard %s: %w", d, err)
		}
		for _, r := range rows {
			if r.Params <= 0 || r.Params > limit || known[r.ModelID] {
				continue
			}
			known[r.ModelID] = true
			item := Discovered{Upstream: r.ModelID, ParamsB: math.Round(float64(r.Params)/1e7) / 100,
				Dataset: d, Task: datasets[d].Task, Value: r.Value}
			base := r.ModelID[strings.LastIndex(r.ModelID, "/")+1:]
			for _, org := range cands.Discover.GGUFOrgs {
				if repo := org + "/" + base + "-GGUF"; src.Exists(ctx, repo) {
					item.GGUF = repo
					break
				}
			}
			out = append(out, item)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Dataset != out[j].Dataset {
			return out[i].Dataset < out[j].Dataset
		}
		return out[i].Upstream < out[j].Upstream
	})
	return out, nil
}

// HF is a Source backed by the public Hugging Face and GitHub HTTP APIs. No
// credentials are needed; GitHubToken only raises rate limits.
type HF struct {
	Client      *http.Client
	HFBase      string // default https://huggingface.co
	GitHubBase  string // default https://api.github.com
	GitHubToken string
}

func (h *HF) hf() string {
	if h.HFBase != "" {
		return h.HFBase
	}
	return "https://huggingface.co"
}

func (h *HF) gh() string {
	if h.GitHubBase != "" {
		return h.GitHubBase
	}
	return "https://api.github.com"
}

func (h *HF) get(ctx context.Context, u string, v any, auth string) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return err
	}
	req.Header.Set("User-Agent", "mote-refresh")
	if auth != "" {
		req.Header.Set("Authorization", "Bearer "+auth)
	}
	c := h.Client
	if c == nil {
		c = &http.Client{Timeout: 60 * time.Second}
	}
	resp, err := c.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		io.Copy(io.Discard, resp.Body)
		return fmt.Errorf("GET %s: %s", u, resp.Status)
	}
	return json.NewDecoder(io.LimitReader(resp.Body, 64<<20)).Decode(v)
}

func (h *HF) RepoFiles(ctx context.Context, repo string) (string, map[string]RemoteFile, error) {
	var info struct {
		SHA string `json:"sha"`
	}
	if err := h.get(ctx, h.hf()+"/api/models/"+repo+"?expand[]=sha", &info, ""); err != nil {
		return "", nil, err
	}
	if len(info.SHA) != 40 {
		return "", nil, fmt.Errorf("%s: no revision", repo)
	}
	var tree []struct {
		Path string `json:"path"`
		Size int64  `json:"size"`
		LFS  *struct {
			OID string `json:"oid"`
		} `json:"lfs"`
	}
	// Recursive, since a diffusers repo keeps its VAE in a vae/ folder.
	if err := h.get(ctx, h.hf()+"/api/models/"+repo+"/tree/"+info.SHA+"?recursive=true", &tree, ""); err != nil {
		return "", nil, err
	}
	files := map[string]RemoteFile{}
	for _, f := range tree {
		if f.LFS != nil {
			files[f.Path] = RemoteFile{SHA256: f.LFS.OID, Size: f.Size}
		}
	}
	return info.SHA, files, nil
}

func (h *HF) Upstream(ctx context.Context, id string) (UpstreamInfo, error) {
	var d struct {
		CardData struct {
			License string `json:"license"`
		} `json:"cardData"`
		Safetensors struct {
			Total int64 `json:"total"`
		} `json:"safetensors"`
		EvalResults []struct {
			Filename string `json:"filename"`
			Verified bool   `json:"verified"`
			Data     struct {
				Dataset struct {
					ID     string `json:"id"`
					TaskID string `json:"task_id"`
				} `json:"dataset"`
				Value  *float64 `json:"value"`
				Date   string   `json:"date"`
				Source struct {
					URL  string `json:"url"`
					Name string `json:"name"`
					User string `json:"user"`
				} `json:"source"`
			} `json:"data"`
		} `json:"evalResults"`
	}
	q := "?expand[]=cardData&expand[]=safetensors&expand[]=evalResults"
	if err := h.get(ctx, h.hf()+"/api/models/"+id+q, &d, ""); err != nil {
		return UpstreamInfo{}, err
	}
	if d.CardData.License == "" {
		return UpstreamInfo{}, fmt.Errorf("%s: license not declared upstream", id)
	}
	info := UpstreamInfo{License: d.CardData.License, ParamsB: float64(d.Safetensors.Total) / 1e9}
	for _, e := range d.EvalResults {
		x := e.Data
		if x.Value == nil || x.Dataset.ID == "" || x.Date == "" {
			continue
		}
		src := x.Source.Name
		if src == "" {
			src = x.Source.User
		}
		u := x.Source.URL
		if !strings.HasPrefix(u, "https://") {
			u = "https://huggingface.co/" + id + "/blob/main/" + url.PathEscape(e.Filename)
		}
		date := x.Date
		if len(date) > 10 {
			date = date[:10]
		}
		info.Evals = append(info.Evals, Eval{Dataset: x.Dataset.ID, Task: x.Dataset.TaskID, Value: *x.Value,
			Verified: e.Verified, Source: src, URL: u, Date: date})
	}
	return info, nil
}

// LatestRelease returns the most recently published release, prerelease or
// not: llama.cpp tags every nightly CI build a prerelease and GitHub's own
// "latest" release (the newest non-prerelease, non-draft one) is not always
// among them, so the releases list, which GitHub returns newest first, is
// used instead of the singular "latest" endpoint.
func (h *HF) LatestRelease(ctx context.Context, repo string) (Release, error) {
	var d []struct {
		Tag       string    `json:"tag_name"`
		Draft     bool      `json:"draft"`
		Published time.Time `json:"published_at"`
		Assets    []struct {
			Name   string `json:"name"`
			URL    string `json:"browser_download_url"`
			Size   int64  `json:"size"`
			Digest string `json:"digest"`
		} `json:"assets"`
	}
	if err := h.get(ctx, h.gh()+"/repos/"+repo+"/releases?per_page=5", &d, h.GitHubToken); err != nil {
		return Release{}, err
	}
	for _, rd := range d {
		if rd.Draft {
			continue
		}
		rel := Release{Tag: rd.Tag, Published: rd.Published, Assets: map[string]RemoteAsset{}}
		for _, a := range rd.Assets {
			rel.Assets[a.Name] = RemoteAsset{URL: a.URL, Size: a.Size, SHA256: strings.TrimPrefix(a.Digest, "sha256:")}
		}
		return rel, nil
	}
	return Release{}, fmt.Errorf("%s has no published release", repo)
}

func (h *HF) Leaderboard(ctx context.Context, dataset string) ([]LeaderboardEntry, error) {
	var rows []LeaderboardEntry
	err := h.get(ctx, h.hf()+"/api/datasets/"+dataset+"/leaderboard", &rows, "")
	return rows, err
}

func (h *HF) Exists(ctx context.Context, repo string) bool {
	var v map[string]any
	return h.get(ctx, h.hf()+"/api/models/"+repo, &v, "") == nil
}
