// Package registry holds mote's machine-readable model metadata and the
// selection policy that picks a model per capability. The default registry is
// generated by cmd/mote-refresh from candidates.json and policy.json and is
// embedded into the binary; `mote update` can install a newer copy.
package registry

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

//go:embed models.json
var embeddedModels []byte

// Schema is the registry format version understood by this binary. 2 added
// runtimes other than llama.cpp (Runtimes) and models built from files in
// several repositories. 3 added a GPU-offloading build of a runtime
// (Asset.Variant).
const Schema = 3

// Capabilities a model can provide. Tasks request capabilities, not models.
var Capabilities = map[string]string{
	"text":    "text -> text",
	"code":    "text/code -> code",
	"extract": "document -> structured data (JSON)",
	"vision":  "image (+text) -> text",
	"asr":     "audio -> text",
	"tts":     "text -> audio",
	"embed":   "text -> vector (routing, search)",
	"image":   "text -> image (minutes on a CPU; downloaded only when used)",
}

// Optional capabilities are left out of setup and profile checks: their
// models are large and slow on a CPU, so they are downloaded the first time
// something needs them, and only on machines with room for them.
var Optional = map[string]bool{"image": true}

// Backends a model can run on, and the file roles each one needs. llama.cpp
// is the main runtime; others are pinned in Registry.Runtimes.
var Backends = map[string][]string{
	"llama.cpp": {"model"},
	"sd.cpp":    {"model", "vae", "llm"},
}

// fileRoles are the roles a backend's files may have.
var fileRoles = map[string]map[string]bool{
	"llama.cpp": {"model": true, "mmproj": true},
	"sd.cpp":    {"model": true, "vae": true, "llm": true},
}

// Benchmark kinds. Only upstream measurements and explicit estimates may
// appear in the repository registry; local measurements live in the user's
// data directory and are never written back here.
const (
	KindUpstream = "upstream"
	KindEstimate = "estimate"
	KindLocal    = "local"
)

type Registry struct {
	Schema    int     `json:"schema"`
	Version   string  `json:"version"`
	Generated string  `json:"generated"`
	Note      string  `json:"note,omitempty"`
	Runtime   Runtime `json:"runtime"`
	// Runtimes pins the runtimes of other backends, such as sd.cpp. They
	// are installed only when a model that needs one is used.
	Runtimes []Runtime                    `json:"runtimes,omitempty"`
	Policy   Policy                       `json:"policy"`
	Models   []Model                      `json:"models"`
	Defaults map[string]map[string]Choice `json:"defaults"`
}

// Runtime pins a release of an inference runtime: llama.cpp, or another
// backend's in Registry.Runtimes. Name is the backend it serves.
type Runtime struct {
	Name      string  `json:"name"`
	Version   string  `json:"version"`
	Published string  `json:"published"`
	License   string  `json:"license"`
	Source    string  `json:"source"`
	Assets    []Asset `json:"assets"`
}

type Asset struct {
	OS   string `json:"os"`
	Arch string `json:"arch"`
	// Variant is empty for the default CPU-only build, or "gpu" for one
	// that can offload inference to a GPU (Vulkan on Linux and Windows;
	// macOS needs none of its own, since the default build already
	// includes Metal).
	Variant string `json:"variant,omitempty"`
	URL     string `json:"url"`
	SHA256  string `json:"sha256"`
	Size    int64  `json:"size"`
}

type Model struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Backend     string   `json:"backend"`
	Upstream    string   `json:"upstream"`
	Repo        string   `json:"repo"`
	Revision    string   `json:"revision"`
	License     string   `json:"license"`
	Quant       string   `json:"quant"`
	ParamsB     float64  `json:"params_b"`
	Caps        []string `json:"caps"`
	Context     int      `json:"context"`
	Args        []string `json:"args,omitempty"`
	OutputAfter string   `json:"output_after,omitempty"`
	// QueryPrefix is prepended to a short query before embedding it.
	// Retrieval encoders are asymmetric: BGE scores a bare question against
	// a description poorly without its instruction prefix.
	QueryPrefix string      `json:"query_prefix,omitempty"`
	Files       []File      `json:"files"`
	RAMEstimate int         `json:"ram_mb_estimate"`
	MinRAMMB    int         `json:"min_ram_mb"`
	Benchmarks  []Benchmark `json:"benchmarks"`
	Notes       string      `json:"notes,omitempty"`
}

type File struct {
	Role   string `json:"role"` // model or mmproj; for sd.cpp also vae and llm
	Name   string `json:"name"`
	URL    string `json:"url"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

type Benchmark struct {
	Kind     string  `json:"kind"`
	Dataset  string  `json:"dataset"`
	Task     string  `json:"task"`
	Value    float64 `json:"value"`
	Verified bool    `json:"verified"`
	Source   string  `json:"source"`
	URL      string  `json:"url"`
	Date     string  `json:"date"`
}

type Policy struct {
	Priorities        []string           `json:"priorities"`
	UsableRAMFraction float64            `json:"usable_ram_fraction"`
	RAMOverheadMB     int                `json:"ram_overhead_mb"`
	Profiles          map[string]Profile `json:"profiles"`
	Gates             map[string]Gate    `json:"gates"`
}

type Profile struct {
	Description     string  `json:"description"`
	MaxRAMMB        int     `json:"max_ram_mb"`
	MinTokensPerSec float64 `json:"min_tokens_per_sec"`
}

// Gate is the quality bar a model must meet for a capability, expressed as an
// upstream benchmark threshold per profile.
type Gate struct {
	Dataset string             `json:"dataset"`
	Task    string             `json:"task"`
	Higher  bool               `json:"higher_is_better"`
	Min     map[string]float64 `json:"threshold"`
	Proxy   bool               `json:"proxy,omitempty"`
	Note    string             `json:"note,omitempty"`
}

type Choice struct {
	Model  string `json:"model"`
	Reason string `json:"reason"`
	Meets  bool   `json:"meets_policy"`
}

// Default returns the registry embedded in the binary.
func Default() *Registry {
	r, err := Parse(embeddedModels)
	if err != nil {
		panic("embedded registry is invalid: " + err.Error())
	}
	return r
}

// ErrOldSchema marks a registry written for an older mote. The one embedded
// in this binary supersedes it.
var ErrOldSchema = errors.New("registry is in an older format")

// Parse decodes and validates a registry document.
func Parse(b []byte) (*Registry, error) {
	// The schema is read on its own first: a registry from a newer mote has
	// fields this one does not know, and saying so beats naming a field.
	var head struct {
		Schema int `json:"schema"`
	}
	if json.Unmarshal(b, &head) == nil && head.Schema > Schema {
		return nil, fmt.Errorf("registry schema %d needs a newer mote (this one reads %d); reinstall mote to update it", head.Schema, Schema)
	}
	if head.Schema > 0 && head.Schema < Schema {
		return nil, fmt.Errorf("%w: schema %d", ErrOldSchema, head.Schema)
	}
	var r Registry
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&r); err != nil {
		return nil, fmt.Errorf("registry: %w", err)
	}
	if err := r.Validate(); err != nil {
		return nil, err
	}
	return &r, nil
}

// Newer reports whether version a is newer than b. Versions are dotted
// numbers (2026.09.26, 2026.09.26.1); non-numeric parts compare as text.
func Newer(a, b string) bool {
	pa, pb := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(pa) || i < len(pb); i++ {
		if i >= len(pa) {
			return false
		}
		if i >= len(pb) {
			return true
		}
		x, errx := strconv.Atoi(pa[i])
		y, erry := strconv.Atoi(pb[i])
		if errx != nil || erry != nil {
			if pa[i] != pb[i] {
				return pa[i] > pb[i]
			}
			continue
		}
		if x != y {
			return x > y
		}
	}
	return false
}

// Model returns the model with the given id.
func (r *Registry) Model(id string) (*Model, bool) {
	for i := range r.Models {
		if r.Models[i].ID == id {
			return &r.Models[i], true
		}
	}
	return nil, false
}

// Asset returns the runtime archive for an OS/arch pair.
func (r *Registry) Asset(goos, arch string) (Asset, bool) { return r.Runtime.Asset(goos, arch) }

// Asset returns the default (CPU-only) build of rt for an OS and
// architecture.
func (rt Runtime) Asset(goos, arch string) (Asset, bool) {
	for _, a := range rt.Assets {
		if a.OS == goos && a.Arch == arch && a.Variant == "" {
			return a, true
		}
	}
	return Asset{}, false
}

// GPUAsset returns the build of rt for an OS and architecture that can
// offload to a GPU, when one is pinned. Most GPU-capable platforms need a
// separate build (Linux and Windows, for Vulkan); one that does not, such
// as macOS, has no entry here and uses Asset instead, under different
// runtime flags.
func (rt Runtime) GPUAsset(goos, arch string) (Asset, bool) {
	for _, a := range rt.Assets {
		if a.OS == goos && a.Arch == arch && a.Variant == "gpu" {
			return a, true
		}
	}
	return Asset{}, false
}

// RuntimeFor returns the pinned runtime a backend runs on.
func (r *Registry) RuntimeFor(backend string) (Runtime, bool) {
	if backend == r.Runtime.Name {
		return r.Runtime, true
	}
	for _, rt := range r.Runtimes {
		if rt.Name == backend {
			return rt, true
		}
	}
	return Runtime{}, false
}

// ProfileNames returns profile names sorted by their RAM ceiling.
func (r *Registry) ProfileNames() []string {
	var names []string
	for n := range r.Policy.Profiles {
		names = append(names, n)
	}
	sort.Slice(names, func(i, j int) bool {
		a, b := r.Policy.Profiles[names[i]], r.Policy.Profiles[names[j]]
		if a.MaxRAMMB != b.MaxRAMMB {
			return a.MaxRAMMB < b.MaxRAMMB
		}
		return names[i] < names[j]
	})
	return names
}

// Has reports whether the model provides capability c.
func (m *Model) Has(c string) bool {
	for _, x := range m.Caps {
		if x == c {
			return true
		}
	}
	return false
}

// File returns the file with the given role.
func (m *Model) File(role string) (File, bool) {
	for _, f := range m.Files {
		if f.Role == role {
			return f, true
		}
	}
	return File{}, false
}

// Bytes is the total download size.
func (m *Model) Bytes() int64 {
	var n int64
	for _, f := range m.Files {
		n += f.Size
	}
	return n
}

// Measurement returns the upstream measurement for a dataset/task, if any.
func (m *Model) Measurement(dataset, task string) (Benchmark, bool) {
	for _, b := range m.Benchmarks {
		if b.Kind == KindUpstream && b.Dataset == dataset && b.Task == task {
			return b, true
		}
	}
	return Benchmark{}, false
}

var (
	idRe     = regexp.MustCompile(`^[a-z0-9][a-z0-9.\-]*$`)
	sha256Re = regexp.MustCompile(`^[0-9a-f]{64}$`)
	fileRe   = regexp.MustCompile(`^[A-Za-z0-9._\-]+$`)
	argRe    = regexp.MustCompile(`^[A-Za-z0-9_.:=\-]+$`)
)

func httpsURL(s string) error {
	u, err := url.Parse(s)
	if err != nil || u.Scheme != "https" || u.Host == "" {
		return fmt.Errorf("%q is not an https URL", s)
	}
	return nil
}

// Validate checks internal consistency. It is strict on purpose: an invalid
// registry is rejected as a whole and the previous one is kept.
func (r *Registry) Validate() error {
	var errs []string
	bad := func(format string, a ...any) { errs = append(errs, fmt.Sprintf(format, a...)) }

	if r.Schema != Schema {
		bad("schema %d not supported (want %d)", r.Schema, Schema)
	}
	if r.Version == "" {
		bad("version is empty")
	}
	if r.Runtime.Name != "llama.cpp" || r.Runtime.Version == "" {
		bad("runtime must be a pinned llama.cpp release")
	}
	checkAssets := func(rt Runtime) {
		seen := map[string]bool{}
		for _, a := range rt.Assets {
			where := fmt.Sprintf("%s asset %s/%s", rt.Name, a.OS, a.Arch)
			if a.Variant != "" {
				where = fmt.Sprintf("%s (%s)", where, a.Variant)
			}
			if a.OS != "linux" && a.OS != "darwin" && a.OS != "windows" {
				bad("%s: unknown os", where)
			}
			if a.Arch != "amd64" && a.Arch != "arm64" {
				bad("%s: unknown arch", where)
			}
			if a.Variant != "" && a.Variant != "gpu" {
				bad("%s: unknown variant", where)
			}
			key := a.OS + "/" + a.Arch + "/" + a.Variant
			if seen[key] {
				bad("%s: pinned twice", where)
			}
			seen[key] = true
			if err := httpsURL(a.URL); err != nil {
				bad("%s: %v", where, err)
			}
			if !strings.HasSuffix(a.URL, ".tar.gz") && !strings.HasSuffix(a.URL, ".zip") {
				bad("%s: unsupported archive %s", where, a.URL)
			}
			if !sha256Re.MatchString(a.SHA256) || a.Size <= 0 {
				bad("%s: missing sha256 or size", where)
			}
		}
	}
	checkAssets(r.Runtime)
	named := map[string]bool{}
	for _, rt := range r.Runtimes {
		if _, ok := Backends[rt.Name]; !ok || rt.Name == "llama.cpp" {
			bad("runtimes: unknown backend %q", rt.Name)
		}
		if named[rt.Name] {
			bad("runtimes: %s pinned twice", rt.Name)
		}
		named[rt.Name] = true
		if rt.Version == "" || rt.License == "" {
			bad("runtimes: %s needs a version and a license", rt.Name)
		}
		checkAssets(rt)
	}

	p := r.Policy
	if len(p.Profiles) == 0 {
		bad("policy: no profiles")
	}
	if p.UsableRAMFraction <= 0 || p.UsableRAMFraction > 1 {
		bad("policy: usable_ram_fraction must be in (0,1]")
	}
	for name, g := range p.Gates {
		if _, ok := Capabilities[name]; !ok {
			bad("policy: gate for unknown capability %q", name)
		}
		if g.Dataset == "" || g.Task == "" {
			bad("policy: gate %q needs dataset and task", name)
		}
		for prof := range p.Profiles {
			if _, ok := g.Min[prof]; !ok {
				bad("policy: gate %q has no threshold for profile %q", name, prof)
			}
		}
	}

	seen := map[string]bool{}
	for _, m := range r.Models {
		where := "model " + m.ID
		if !idRe.MatchString(m.ID) {
			bad("%s: invalid id", where)
		}
		if seen[m.ID] {
			bad("%s: duplicate id", where)
		}
		seen[m.ID] = true
		roles, known := Backends[m.Backend]
		if !known {
			bad("%s: unknown backend %q", where, m.Backend)
		} else if _, pinned := r.RuntimeFor(m.Backend); !pinned {
			bad("%s: backend %s has no pinned runtime", where, m.Backend)
		}
		for _, role := range roles {
			if _, ok := m.File(role); !ok {
				bad("%s: %s models need a %s file", where, m.Backend, role)
			}
		}
		if len(m.Caps) == 0 {
			bad("%s: no capabilities", where)
		}
		needsProj := false
		for _, c := range m.Caps {
			if _, ok := Capabilities[c]; !ok {
				bad("%s: unknown capability %q", where, c)
			}
			if m.Backend == "llama.cpp" && (c == "vision" || c == "asr" || c == "tts") {
				needsProj = true
			}
			if (c == "image") != (m.Backend == "sd.cpp") {
				bad("%s: image generation runs on sd.cpp, and sd.cpp only generates images", where)
			}
		}
		// A context window is a language model's; sd.cpp has none.
		if m.Backend == "llama.cpp" && m.Context <= 0 {
			bad("%s: context must be set explicitly", where)
		}
		if m.License == "" {
			bad("%s: license is required", where)
		}
		if _, ok := m.File("mmproj"); needsProj && !ok {
			bad("%s: capabilities %v require an mmproj file", where, m.Caps)
		}
		for _, f := range m.Files {
			if !fileRoles[m.Backend][f.Role] {
				bad("%s: unknown file role %q for %s", where, f.Role, m.Backend)
			}
			if !fileRe.MatchString(f.Name) {
				bad("%s: unsafe file name %q", where, f.Name)
			}
			if err := httpsURL(f.URL); err != nil {
				bad("%s: %v", where, err)
			}
			if !sha256Re.MatchString(f.SHA256) || f.Size <= 0 {
				bad("%s: file %s needs sha256 and size", where, f.Name)
			}
		}
		for _, a := range m.Args {
			if !argRe.MatchString(a) {
				bad("%s: suspicious runtime argument %q", where, a)
			}
		}
		for _, b := range m.Benchmarks {
			switch b.Kind {
			case KindUpstream:
				if err := httpsURL(b.URL); err != nil {
					bad("%s: upstream benchmark %s/%s needs a source URL", where, b.Dataset, b.Task)
				}
				if b.Date == "" {
					bad("%s: upstream benchmark %s/%s has no date", where, b.Dataset, b.Task)
				}
			case KindEstimate:
			case KindLocal:
				bad("%s: local measurements do not belong in the shared registry", where)
			default:
				bad("%s: unknown benchmark kind %q", where, b.Kind)
			}
		}
	}

	for prof, caps := range r.Defaults {
		if _, ok := p.Profiles[prof]; !ok {
			bad("defaults: unknown profile %q", prof)
		}
		for c, ch := range caps {
			if _, ok := Capabilities[c]; !ok {
				bad("defaults: unknown capability %q", c)
			}
			m, ok := r.Model(ch.Model)
			if !ok {
				bad("defaults: %s/%s references unknown model %q", prof, c, ch.Model)
			} else if !m.Has(c) {
				bad("defaults: %s/%s model %q lacks that capability", prof, c, ch.Model)
			}
		}
	}

	if len(errs) > 0 {
		sort.Strings(errs)
		return fmt.Errorf("invalid registry:\n  %s", strings.Join(errs, "\n  "))
	}
	return nil
}
